### ISSUE TITLE
Wrong rotation angle of converted 3D bounding box labels

### ISSUE THREAD

**Issue by kyrie-louy** [ZiadElmassik/CADCD_TO_KITTI_COMPLETE#1]
Hi @ZiadElmassik, thanks for your great work. It helps me a lot!

However, after I converted CADCD to KITTI and visualized it, I found that **the rotation angle of the ground truth 3D bounding box for many objects is incorrect**. And this issue exists in each frame (both 2018 and 2019 samples).

Here I select the frame `cadcd/2018_03_06/0001/labeled/image_00/data/0000000045.png` for your reference. We can see that the GT bbox of the front car, as well as the GT bbox of vehicles on the right side, have very strange angles.

3D view:
![github1](https://user-images.githubusercontent.com/40813399/181022636-bcc76222-2c46-4600-825f-1442236ab196.png)
BEV view:
![github2](https://user-images.githubusercontent.com/40813399/181022681-32ef45da-bbb3-4bc7-9ce3-eefbb16f4260.png)
Camera view:
![github3](https://user-images.githubusercontent.com/40813399/181022700-03087dfb-83c9-4214-b1ae-5181f10e2fbe.png)

I wonder that have you encountered such an issue? And what may be the possible reason?

Note that I follow the instruction in README to comment, and I also repeat the visualization through the tools in [second.pytorch](https://github.com/traveller59/second.pytorch) and [kitti_obj_vis](https://github.com/kuixu/kitti_object_vis).

**Comment by ZiadElmassik** [comment]
Hello @kyrie-louy. Thank you for bring this problem to my attention. I've just resolved it and have pushed the updated script. Now, try the conversion again, and it should be accurate.

**Comment by kyrie-louy** [comment]
Hi @ZiadElmassik. Thank you for your prompt reply! The problem for the 3D bounding box is resolved, while the corresponding 2D bounding boxes went wrong:

2D boxes:
![2dbox_screenshot_27 07 2022](https://user-images.githubusercontent.com/40813399/181150884-8e910ee0-9fab-4703-ad4d-0e5ff77cd398.png)

3D boxes:
![3dbox_screenshot_27 07 2022](https://user-images.githubusercontent.com/40813399/181150910-3b96b88a-9041-4d1b-ac5e-e3cda08c99f1.png)

I'm also trying to figure out this issue.



> Hello @kyrie-louy. Thank you for bring this problem to my attention. I've just resolved it and have pushed the updated script. Now, try the conversion again, and it should be accurate.

**Comment by ZiadElmassik** [comment]
Alright no worries @kyrie-louy, I'll work on it and respond to you with a solution in a few hours.

**Comment by ZiadElmassik** [comment]
Alright @kyrie-louy, the 2D bounding boxes are fixed along with the 3D rotations of the 3D bounding boxes. I just pushed the updated script. Please, try the conversion again.

**Comment by kyrie-louy** [comment]
> Alright @kyrie-louy, the 2D bounding boxes are fixed along with the 3D rotations of the 3D bounding boxes. I just pushed the updated script. Please, try the conversion again.

Yeah, I see the reason, and everything looks fine now. Many thanks for providing the solution!
